version: '3.7'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 9000:9000
    depends_on:
      - db
    volumes:
      - ./app:/root:rw,cached

  db:
    image: 'postgres:latest'
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - postgres-network
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/

networks: 
  postgres-network:
    driver: bridge